### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by dvjn** [dvjn/woodpecker-docker-tags-plugin#2]
- [ ] add recipes for common use-cases #3
- [ ] add support for global expressions ([reference](https://github.com/docker/metadata-action/tree/master?tab=readme-ov-file#global-expressions)) #4
- [ ] write unit tests for all commands (using something like [shunit2](https://github.com/kward/shunit2)) #5
- [ ] add plugin to woodpecker docs #6
